# Purpose : Find any occurrence of ''SET ANSI_PADDING OFF'' in *.sch files
#    generated by snapshot agent and replace it with ''SET ANSI_PADDING ON'' which
#   is the required setting for replication
# Comments: Script would loop through specified folder and find all files with sch extension
#    in current folder and its sub-folders. It would be added as third step in each
#   snapshot job created by default whenever publication is created. 
# Script  : PowerShell 1.0

foreach ($file in get-Childitem D:\ReplData\unc\DEVSQL2016_DARTADMIN_GROUP1_PUB\20190425232130 -include *.sch -recurse | 
 Sort-Object extension, length -descending)
{
    $file.fullname + "`t " + $file.name + "`t " +$file.length + "`t " +    $file.LastAccessTime

    (Get-Content $file.fullname) | 
    Foreach-Object {$_ -replace "SET ANSI_PADDING OFF", "SET ANSI_PADDING ON"} | 
    Set-Content $file.fullname
}